#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("elmar.droid.Resource", IsApplication=true)]

namespace elmar.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_keyboard_voice_white_48dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_settings_applications_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_settings_applications_white_36dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_settings_applications_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int inputLanguage = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int inputLanguageRow = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int outputLanguage = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int outputLanguageRow = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int preferences = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int startVoice = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int logo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int InputLanguage = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int NotRecognized = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int OutputLanguage = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Divider = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int DividerVertical = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SettingsEntry = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SettingsEntryText = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int SettingsEntryValue = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
