#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("elmar.droid.Resource", IsApplication=true)]

namespace elmar.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::elmar.droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::elmar.droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add_circle_white_36dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_circle_white_48dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_delete_white_48dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_done_white_48dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_keyboard_arrow_down_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_keyboard_arrow_up_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_keyboard_voice_white_48dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_settings_applications_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_settings_applications_white_36dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_settings_applications_white_48dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int add_command = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int add_step = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int commandName = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int commandText = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int command_list = 2131099659;
			
			// aapt resource value: 0x7f060018
			public const int commandsRow = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int eventActivated = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int eventName = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int eventOutput = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int event_list = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int eventsRow = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int inputCommandName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int inputCommandNameRow = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int inputCommandText = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int inputCommandTextRow = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int inputLanguage = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int inputLanguageRow = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int moveDownOrder = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int moveUpOrder = 2131099658;
			
			// aapt resource value: 0x7f060016
			public const int outputLanguage = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int outputLanguageRow = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int preferences = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int startVoice = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int stepList = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int stepName = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Command = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int command_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int command_step_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Commands = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int event_item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Events = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int logo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Settings = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int CommandName = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int CommandSteps = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int CommandText = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int Commands = 2130968589;
			
			// aapt resource value: 0x7f040003
			public const int DeleteCommand = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int Events = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int InputLanguage = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int NotRecognized = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int OutputLanguage = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int OutputText = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int SMSReceivingEvent = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int SaveCommand = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int ShutdownEvent = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Divider = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int DividerVertical = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SettingsEntry = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SettingsEntryText = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int SettingsEntryValue = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
